import { useState, useEffect } from 'react'
import { Flame, CheckCircle2, Plus, Trash2 } from 'lucide-react'
import api from '../../lib/api'

interface HabitItem {
  id: number
  name: string
  frequency: string
  streak_count: number
  last_completed_at?: string
}

export default function HabitsSection() {
  const [habits, setHabits] = useState<HabitItem[]>([])
  const [newHabitName, setNewHabitName] = useState('')
  const [isCreating, setIsCreating] = useState(false)

  useEffect(() => {
    fetchHabits()
  }, [])

  const fetchHabits = async () => {
    try {
      const res = await api.get('/habits/')
      const fetched: HabitItem[] = Array.isArray(res.data) ? res.data : []
      setHabits(fetched)
    } catch (err) {
      console.error('Failed to fetch habits:', err)
      setHabits([])
    }
  }

  const notifyDataChanged = () => {
    window.dispatchEvent(new Event('lifeos_data_updated'))
  }

  const handleCompleteHabit = async (id: number) => {
    try {
      setHabits((prev) =>
        prev.map((h) => (h.id === id ? { ...h, streak_count: h.streak_count + 1 } : h))
      )
      await api.post(`/habits/${id}/complete`)
      notifyDataChanged()
    } catch (err) {
      console.error('Failed to complete habit:', err)
    }
  }

  const handleCreateHabit = async (e: React.FormEvent) => {
    e.preventDefault()
    if (!newHabitName.trim()) return

    setIsCreating(true)
    try {
      const res = await api.post('/habits/', {
        name: newHabitName.trim(),
        frequency: 'daily',
        streak_count: 1
      })
      if (res.data) {
        setHabits((prev) => [res.data, ...prev])
      }
      setNewHabitName('')
      notifyDataChanged()
    } catch (err) {
      console.error('Failed to create habit:', err)
      setNewHabitName('')
    } finally {
      setIsCreating(false)
    }
  }

  const handleDeleteHabit = async (id: number) => {
    try {
      await api.delete(`/habits/${id}`)
      setHabits((prev) => prev.filter((h) => h.id !== id))
      notifyDataChanged()
    } catch (err) {
      console.error('Failed to delete habit:', err)
      setHabits((prev) => prev.filter((h) => h.id !== id))
      notifyDataChanged()
    }
  }

  return (
    <div className='bg-white rounded-2xl p-6 border border-slate-200/80 shadow-sm space-y-5'>
      <div className='flex items-center justify-between border-b border-slate-100 pb-4'>
        <div>
          <h3 className='text-lg font-serif font-bold text-slate-900 tracking-tight flex items-center gap-2'>
            <Flame className='w-5 h-5 text-amber-500 fill-amber-500' />
            <span>Daily Habits & Streaks</span>
          </h3>
          <p className='text-xs text-slate-500 mt-0.5'>
            Auto-generated by AI Agents & tracked daily
          </p>
        </div>

        <span className='px-3 py-1 rounded-full bg-amber-50 border border-amber-100 text-amber-700 text-xs font-extrabold flex items-center gap-1'>
          <Flame className='w-3.5 h-3.5 fill-amber-500 text-amber-500' />
          <span>{habits.reduce((acc, h) => acc + h.streak_count, 0)} total streak days</span>
        </span>
      </div>

      {/* Add Habit Form */}
      <form onSubmit={handleCreateHabit} className='flex gap-2'>
        <input
          type='text'
          value={newHabitName}
          onChange={(e) => setNewHabitName(e.target.value)}
          placeholder='Add custom habit (e.g. "30 mins LeetCode practice")...'
          className='flex-1 px-3.5 py-2 text-xs bg-slate-50 dark:bg-slate-950 border border-slate-300 dark:border-slate-800 rounded-xl focus:outline-none focus:ring-2 focus:ring-amber-500 text-slate-900 dark:text-slate-100 placeholder-slate-400 dark:placeholder-slate-600 font-sans'
        />
        <button
          type='submit'
          disabled={isCreating || !newHabitName.trim()}
          className='px-3.5 py-2 bg-amber-500 hover:bg-amber-400 text-white font-medium text-xs rounded-xl transition-colors disabled:opacity-50 flex items-center gap-1 shrink-0 shadow-sm'
        >
          <Plus className='w-3.5 h-3.5' />
          <span>Add Habit</span>
        </button>
      </form>

      {/* Habits List */}
      {habits.length === 0 ? (
        <div className='p-6 bg-slate-50/60 dark:bg-slate-950/60 rounded-xl border border-slate-200/60 dark:border-slate-800 text-center text-xs text-slate-400'>
          No habits tracked yet. Add your first habit above to start building daily streaks!
        </div>
      ) : (
        <div className='grid grid-cols-1 md:grid-cols-3 gap-4'>
          {habits.map((habit) => (
          <div
            key={habit.id}
            className='group p-4 bg-slate-50/70 dark:bg-slate-950/70 rounded-xl border border-slate-200/70 dark:border-slate-800 hover:border-amber-300 transition-all flex flex-col justify-between space-y-3'
          >
            <div className='flex items-start justify-between gap-2'>
              <div>
                <span className='text-xs font-bold uppercase tracking-wider text-amber-600 dark:text-amber-400 bg-amber-50 dark:bg-amber-950/40 px-2 py-0.5 rounded border border-amber-100 dark:border-amber-900 inline-block mb-1.5'>
                  {habit.frequency}
                </span>
                <h4 className='text-sm font-semibold text-slate-900 dark:text-slate-100 block leading-snug'>
                  {habit.name}
                </h4>
              </div>

              <button
                onClick={() => handleDeleteHabit(habit.id)}
                className='opacity-0 group-hover:opacity-100 text-slate-400 hover:text-red-600 transition-opacity p-1'
                title='Delete habit'
              >
                <Trash2 className='w-3.5 h-3.5' />
              </button>
            </div>

            <div className='flex items-center justify-between pt-2 border-t border-slate-200/50'>
              <div className='flex items-center gap-1.5 text-xs font-extrabold text-amber-600'>
                <Flame className='w-4 h-4 fill-amber-500 text-amber-500 animate-pulse' />
                <span>{habit.streak_count} day streak</span>
              </div>

              <button
                onClick={() => handleCompleteHabit(habit.id)}
                className='inline-flex items-center gap-1 px-3 py-1.5 bg-emerald-500 hover:bg-emerald-600 text-white rounded-lg text-xs font-semibold shadow-xs transition-all active:scale-95'
                title='Check off for today'
              >
                <CheckCircle2 className='w-3.5 h-3.5' />
                <span>Check off</span>
              </button>
            </div>
          </div>
        ))}
        </div>
      )}
    </div>
  )
}
